#!/bin/bash

#delete links
rm -rf ~/.w3m
rm ~/.gitconfig
rm ~/.irbrc
rm ~/.bashrc
rm ~/.bash_profile
rm ~/.ctags
rm ~/bin
rm ~/.vimrc
rm -rf ~/.vim
rm ~/.gvimrc
rm ~/.tmux.conf

#vim
ln -s ~/src/git/github/tluna/vim/vimrc        ~/.vimrc
ln -s ~/src/git/github/tluna/vim/gvimrc       ~/.gvimrc

#another dot files and w3m
ln -s ~/src/git/github/tluna/w3m/             ~/.w3m
ln -s ~/src/git/github/tluna/gitconfig        ~/.gitconfig
ln -s ~/src/git/github/tluna/irbrc            ~/.irbrc
ln -s ~/src/git/github/tluna/tmux.conf        ~/.tmux.conf
ln -s ~/src/git/github/tluna/ctags            ~/.ctags
ln -s ~/src/git/github/tluna/bin              ~/bin

#bash
ln -s ~/src/git/github/tluna/environments/mac/bashrc_mac              ~/.bashrc
ln -s ~/src/git/github/tluna/environments/mac/bash_profile_mac        ~/.bash_profile

#git settings
git config --global user.name "t1una"
git config --global user.email "totugekiluna@gmail.com"
git config --global core.editor 'vim -c "set fenc=utf-8"'
git config --global push.default matching

#submoudle
cd ~/src/git/github/tluna/
git submodule init
git submodule update

cp -rf ~/src/git/github/tluna/vim ~/.vim
rm ~/.vim/gvimrc
rm ~/.vim/vimrc
rm ~/.vim/vimrc-work

#cpanm
#cd /Volumes/3tv1/src/git/github/tluna/bin/
#curl -LOk http://xrl.us/cpanm
#chmod u+x cpanm
