export PATH=~/.anyenv/bin:/usr/local/bin:$PATH
if [ -e "$HOME/.anyenv" ]
then
    export ANYENV_ROOT="$HOME/.anyenv"
    export PATH="$ANYENV_ROOT/bin:$PATH"
    if command -v anyenv 1>/dev/null 2>&1
    then
	ANYENV_INIT=~/init/anyenvinit
	[[ ! -e "$ANYENV_INIT" ]] && anyenv init - > "$ANYENV_INIT"

	source "$ANYENV_INIT"

	PYENV_VIRTUALENV_INIT=~/init/pyenv-virtualenv-init
	[[ ! -e "$PYENV_VIRTUALENV_INIT" ]] && pyenv virtualenv-init - > "$PYENV_VIRTUALENV_INIT"

	source "$PYENV_VIRTUALENV_INIT"
    fi
fi

if [ -e "/opt/nvim-linux64/bin" ]
then
    export PATH="/opt/nvim-linux64/bin:$PATH"
fi

if [ -e "~/bin" ]
then
    export PATH="~/bin:$PATH"
fi

export EDITOR=nvim
export PAGER='lv -c'
export LANG='ja_JP.UTF-8'

if command -v nvim 1>/dev/null 2>&1
then
    alias vim=nvim
fi

. "$HOME/.cargo/env"
source ~/.zshenv-local
