# emacs bind
bindkey -e

fpath=(~/.zfunc $fpath)
# cdr, add-zsh-hook を有効にする
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook compinit
add-zsh-hook chpwd chpwd_recent_dirs
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit -i

if type "kubectl" > /dev/null 2>&1; then
  KUBECTL_COMPLETION=~/init/kubectl-completion
  [[ ! -e "$KUBECTL_COMPLETION" ]] && kubectl completion zsh > "$KUBECTL_COMPLETION"

  source $KUBECTL_COMPLETION
fi
if type "helm" > /dev/null 2>&1; then
  HELM_COMPLETION=~/init/helm-completion
  [[ ! -e "$HELM_COMPLETION" ]] && helm completion zsh > "$HELM_COMPLETION"

  source $HELM_COMPLETION
fi

# cdr の設定
zstyle ':completion:*' recent-dirs-insert both
zstyle ':chpwd:*' recent-dirs-max 500
zstyle ':chpwd:*' recent-dirs-default true
zstyle ':chpwd:*' recent-dirs-file "$HOME/.cache/shell/chpwd-recent-dirs"
zstyle ':chpwd:*' recent-dirs-pushd true
zstyle ':completion:*:*:make:*' tag-order 'targets'


# fzf-cdr
alias cdd='fzf-cdr'
function fzf-cdr() {
  target_dir=`cdr -l | sed 's/^[^ ][^ ]*  *//' | fzf`
  target_dir=`echo ${target_dir/\~/$HOME}`
  if [ -n "$target_dir" ]; then
    cd $target_dir
  fi
}

alias co='git checkout $(git branch -a | tr -d " " |fzf --height 100% --prompt "CHECKOUT BRANCH>" --preview "git log --color=always {}" | head -n 1 | sed -e "s/^\*\s*//g" | perl -pe "s/remotes\/origin\///g")'

snap_bin_path="/snap/bin"
if [ -n "${PATH##*${snap_bin_path}}" -a -n "${PATH##*${snap_bin_path}:*}" ]; then
    export PATH=$PATH:${snap_bin_path}
fi

export PATH=/opt/nvim-linux64/bin:$PATH

# nvim
alias vim='nvim'
#aws
if type "aws" > /dev/null 2>&1; then
  complete -C '/usr/local/bin/aws_completer' aws
fi

#xc
if type "xc" > /dev/null 2>&1; then
  complete -o nospace -C ~/.anyenv/envs/goenv/shims/xc xc
fi

# starship
#eval "$(starship init zsh)"
if type "starship" > /dev/null 2>&1; then
  STARSHIP_INIT=~/init/startship-completion
  [[ ! -e "$STARSHIP_INIT" ]] && /usr/local/bin/starship init zsh --print-full-init > "$STARSHIP_INIT"
  
  source "$STARSHIP_INIT"
fi

#brew
BREW_PATH=/home/linuxbrew/.linuxbrew/bin
if [ -e "$BREW_PATH" ]; then
  export PATH="$BREW_PATH:$PATH"
fi

if [ -f ~/.zshrc-local ]; then
  source ~/.zshrc-local
fi

