# emacs bind
bindkey -e

fpath=(~/.zfunc $fpath)
# cdr, add-zsh-hook を有効にする
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook compinit
autoload -Uz compinit && compinit -i
add-zsh-hook chpwd chpwd_recent_dirs
if type "kubectl" > /dev/null 2>&1; then
  source <(kubectl completion zsh)
fi
if type "helm" > /dev/null 2>&1; then
  source <(helm completion zsh)
fi

# cdr の設定
zstyle ':completion:*' recent-dirs-insert both
zstyle ':chpwd:*' recent-dirs-max 500
zstyle ':chpwd:*' recent-dirs-default true
zstyle ':chpwd:*' recent-dirs-file "$HOME/.cache/shell/chpwd-recent-dirs"
zstyle ':chpwd:*' recent-dirs-pushd true
zstyle ':completion:*:*:make:*' tag-order 'targets'


# fzf-cdr
alias cdd='fzf-cdr'
function fzf-cdr() {
  target_dir=`cdr -l | sed 's/^[^ ][^ ]*  *//' | fzf`
  target_dir=`echo ${target_dir/\~/$HOME}`
  if [ -n "$target_dir" ]; then
    cd $target_dir
  fi
}

alias co='git checkout $(git branch -a | tr -d " " |fzf --height 100% --prompt "CHECKOUT BRANCH>" --preview "git log --color=always {}" | head -n 1 | sed -e "s/^\*\s*//g" | perl -pe "s/remotes\/origin\///g")'

snap_bin_path="/snap/bin"
if [ -n "${PATH##*${snap_bin_path}}" -a -n "${PATH##*${snap_bin_path}:*}" ]; then
    export PATH=$PATH:${snap_bin_path}
fi

export PATH=/opt/nvim/nvim-linux64/bin:$PATH

# nvim
alias vim='nvim'

#aws
if type "aws" > /dev/null 2>&1; then
  autoload bashcompinit && bashcompinit
  autoload -Uz compinit && compinit
  complete -C '/usr/local/bin/aws_completer' aws
fi

#xc
if type "xc" > /dev/null 2>&1; then
  autoload -U +X bashcompinit && bashcompinit
  complete -o nospace -C ~/.anyenv/envs/goenv/shims/xc xc
fi

# starship
eval "$(starship init zsh)"

