if has("win32") || has("win64")
  set guifont=Osaka−等幅:h09:cSHIFTJIS
elseif has("mac")
  set guifont=Osaka-Mono:h13
  set transparency=30
  colorscheme torte
endif

" ツールバーを削除
set guioptions-=T

"メニューを削除
set guioptions-=m
