onboarding = false

[ui.toast]
delivery = "system"

[ui]
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"
[theme]
name = "catppuccin"
auto_switch = false

[experimental]
pane_history = true
switch_ascii_input_source_in_prefix = true

[keys]
previous_agent = "prefix+alt+p"
next_agent = "prefix+alt+n"

[ui.sound]
enabled = true
