#!/bin/bash

#delete links
rm -rf ~/.w3m
rm ~/.gitconfig
rm ~/.irbrc
rm ~/.bashrc
if [ -e /etc/debian_version ]; then
  rm ~/.profile
else
  rm ~/.bash_profile
fi
rm ~/.ctags
rm ~/bin
rm ~/.vimrc
rm ~/.gvimrc
rm -rf  ~/.vim
rm ~/.tmux.conf
rm ~/.my.cnf

#vim
ln -s ~/src/git/github/tluna/vim/vimrc        ~/.vimrc
ln -s ~/src/git/github/tluna/vim/gvimrc       ~/.gvimrc
ln -s ~/src/git/github/tluna/vim              ~/.vim

#another dot files and w3m

ln -s ~/src/git/github/tluna/w3m/             ~/.w3m
ln -s ~/src/git/github/tluna/gitconfig        ~/.gitconfig
ln -s ~/src/git/github/tluna/irbrc            ~/.irbrc
ln -s ~/src/git/github/tluna/tmux.conf        ~/.tmux.conf
ln -s ~/src/git/github/tluna/ctags            ~/.ctags
ln -s ~/src/git/github/tluna/bin/             ~/bin
ln -s ~/src/git/github/tluna/dotfiles/my.cnf  ~/.my.cnf

#bash
if [ -e /etc/redhat-release ]; then
  if [ `hostname` == 'edge' ]; then
     ln -s ~/src/git/github/tluna/environments/linux/bashrc/homeserver_e420              ~/.bashrc
     ln -s ~/src/git/github/tluna/environments/linux/bash_profile/homeserver_e420        ~/.bash_profile
  elif [ `hostname` == 'express5100' ]; then 
     ln -s ~/src/git/github/tluna/environments/linux/bashrc/homeserver_express5100       ~/.bashrc
     ln -s ~/src/git/github/tluna/environments/linux/bash_profile/homeserver_express5100 ~/.bash_profile
  fi
elif [ -e /etc/debian_version ]; then
  ln -s ~/src/git/github/tluna/environments/linux/bashrc/debian_e420                     ~/.bashrc
  ln -s ~/src/git/github/tluna/environments/linux/bash_profile/debian_e420               ~/.profile
fi

#git settings
git config --global user.name "t1una"
git config --global user.email "totugekiluna@gmail.com"
git config --global core.editor 'vim -c "set fenc=utf-8"'
git config --global push.default matching

#submoudle
cd ~/src/git/github/tluna/
git submodule init
git submodule update
