#!/bin/bash

#delete links
unlink ~/.w3m
unlink ~/.gitconfig
unlink ~/.irbrc
unlink ~/.bashrc
if [ -e /etc/debian_version ]; then
  unlink ~/.profile
else
  unlink ~/.bash_profile
fi
unlink ~/.ctags
unlink ~/bin
unlink ~/.vimrc
unlink ~/.gvimrc
unlink ~/.vim
unlink ~/.tmux.conf
unlink ~/.my.cnf
unlink ~/.anyenv

#vim
ln -s ~/src/git/github/tluna/vim/vimrc        ~/.vimrc
ln -s ~/src/git/github/tluna/vim/gvimrc       ~/.gvimrc
ln -s ~/src/git/github/tluna/vim/             ~/.vim

#another dot files and w3m
ln -s ~/src/git/github/tluna/w3m/             ~/.w3m
ln -s ~/src/git/github/tluna/gitconfig        ~/.gitconfig
ln -s ~/src/git/github/tluna/irbrc            ~/.irbrc
ln -s ~/src/git/github/tluna/tmux.conf        ~/.tmux.conf
ln -s ~/src/git/github/tluna/ctags            ~/.ctags
ln -s ~/src/git/github/tluna/bin/             ~/bin
ln -s ~/src/git/github/tluna/dotfiles/my.cnf  ~/.my.cnf

#bash
if [ -e /etc/redhat-release ]; then
  #if [ `hostname` == 'tluna' ]; then
     ln -s ~/src/git/github/tluna/environments/linux/bashrc/redhat              ~/.bashrc
     ln -s ~/src/git/github/tluna/environments/linux/bash_profile/redhat        ~/.bash_profile
  #fi
elif [ -e /etc/debian_version ]; then
  #if [ `hostname` == 'tluna' ]; then
     ln -s ~/src/git/github/tluna/environments/linux/bashrc/debian              ~/.bashrc
     ln -s ~/src/git/github/tluna/environments/linux/bash_profile/debian        ~/.profile
  #fi
fi

#git settings
git config --global user.name "t1una"
git config --global user.email "totugekiluna@gmail.com"
git config --global core.editor 'vim -c "set fenc=utf-8"'
git config --global push.default matching

#submoudle
cd ~/src/git/github/tluna/
git submodule init
git submodule update
