#!/bin/bash
case "$1" in
  start)
  thin start -C config/thin.yml
  ;;
  stop)
  thin stop -C config/thin.yml
  ;;
  restart)
  thin stop -C config/thin.yml
  thin start -C config/thin.yml
  ;;
  *)
  echo "Usage: start|stop|restart"
esac
